// Generated by scripts/generate_contracts.py. Do not edit.
import { RuntimeTransport } from "./transport.js";

export type ErrorDetail = { "code": string; "message": string };
export type ErrorResponse = { "error": ErrorDetail };
export type HealthResponse = { "status": "available"; "package_version": string; "api_version": string };
export type ProviderHealth = { "status": "available" | "unavailable" | "inconclusive"; "authenticated": boolean | null; "installed": boolean | null; "compatible": boolean | null; "detail_code": string | null; "effective_model": string | null };
export type Capabilities = { "text_generation": boolean; "structured_output": boolean; "tool_requests": boolean; "token_streaming": boolean; "conversation_continuation": boolean; "model_discovery": boolean; "token_limit_control": boolean };
export type ReasoningProfile = { "id": string; "provider_id": string; "driver": string; "model": string; "configured": boolean; "processing": "local" | "external"; "allow_private_processing": boolean; "qualified_tasks": Array<string>; "qualification": { "status": "qualified" | "unqualified"; "tasks": Array<string> }; "selected": boolean; "capabilities": Capabilities; "health"?: ProviderHealth };
export type ProfilesResponse = { "selected_profile": string; "profiles": Array<ReasoningProfile> };
export type SelectionRequest = { "profile_id": string };
export type ToolDefinition = { "name": string; "description": string; "input_schema": Record<string, unknown> };
export type ToolRequest = { "id": string; "name": string; "arguments": Record<string, unknown> };
export type ToolResult = { "request_id": string; "name": string; "output": unknown; "is_error": boolean };
export type ToolResultsRequest = { "results": Array<ToolResult> };
export type SessionRequest = { "prompt": string; "instructions"?: string; "profile_id"?: string; "task_code"?: string; "private_processing"?: boolean; "allow_external_processing"?: boolean; "tools"?: Array<ToolDefinition>; "output_schema"?: Record<string, unknown> };
export type InputRequest = { "prompt": string };
export type SessionResponse = { "id": string; "profile_id": string; "provider_id": string; "adapter": string; "requested_model": string; "created_at": string; "updated_at": string; "finished_at": string | null; "processing": "local" | "external"; "task_code": string | null; "status": "created" | "running" | "waiting_for_tool" | "completed" | "failed" | "canceled"; "pending_tools": Array<ToolRequest>; "tool_rounds": number; "final_text": string | null; "failure": ErrorDetail | null; "effective_model": string | null; "effective_upstream": string | null; "usage": Record<string, number>; "limits": ReasoningLimits; "validation": "pending" | "passed" | "failed" | "not_validated"; "event_count": number };
export type SessionEvent = { "sequence": number; "type": string; "occurred_at": string; "payload": Record<string, unknown> };
export type EventsResponse = { "events": Array<SessionEvent> };
export type EmbeddingLimits = { "batch_size": number; "max_input_chars": number; "max_batch_chars": number; "timeout_seconds": number; "max_response_bytes": number };
export type ReasoningLimits = { "timeout_seconds": number; "max_input_chars": number; "max_output_chars": number; "max_output_tokens": number; "max_tool_rounds": number };
export type EmbeddingProfile = { "id": string; "provider_id": string; "driver": string; "model": string; "dimensions": number; "processing": "local" | "external"; "profile_fingerprint": string; "document_prefix": string; "query_prefix": string; "revision": string; "normalization": string; "distance_metric": string; "limits": EmbeddingLimits; "allow_private_processing": boolean; "capabilities": { "text_embeddings": boolean; "batching": boolean; "streaming": boolean } };
export type EmbeddingProfilesResponse = { "profiles": Array<EmbeddingProfile> };
export type EmbeddingRequest = { "profile_id": string; "inputs": Array<string>; "purpose": "document" | "query"; "expected_fingerprint"?: string; "allow_external_processing"?: boolean; "private_processing"?: boolean };
export type EmbeddingResponse = { "profile_id": string; "provider_id": string; "adapter": string; "profile_fingerprint": string; "purpose": "document" | "query"; "requested_model": string; "effective_model": string | null; "effective_upstream": string | null; "processing": "local" | "external"; "dimensions": number; "vectors": Array<Array<number>>; "started_at": string; "finished_at": string; "usage": Record<string, number>; "validation": "passed" };

export class RuntimeClient extends RuntimeTransport {
  health(signal?: AbortSignal): Promise<HealthResponse> {
    return this.request<HealthResponse>("/v1/health", "GET", undefined, signal);
  }
  profiles(includeHealth = false, signal?: AbortSignal): Promise<ProfilesResponse> {
    return this.request<ProfilesResponse>("/v1/profiles" + "?health=" + String(includeHealth), "GET", undefined, signal);
  }
  selectProfile(body: SelectionRequest, signal?: AbortSignal): Promise<ProfilesResponse> {
    return this.request<ProfilesResponse>("/v1/selection", "POST", body, signal);
  }
  createSession(body: SessionRequest, signal?: AbortSignal): Promise<SessionResponse> {
    return this.request<SessionResponse>("/v1/sessions", "POST", body, signal);
  }
  session(sessionId: string, signal?: AbortSignal): Promise<SessionResponse> {
    return this.request<SessionResponse>("/v1/sessions/" + encodeURIComponent(sessionId) + "", "GET", undefined, signal);
  }
  events(sessionId: string, after = 0, signal?: AbortSignal): Promise<EventsResponse> {
    return this.request<EventsResponse>("/v1/sessions/" + encodeURIComponent(sessionId) + "/events" + "?after=" + String(after), "GET", undefined, signal);
  }
  continueSession(sessionId: string, body: InputRequest, signal?: AbortSignal): Promise<SessionResponse> {
    return this.request<SessionResponse>("/v1/sessions/" + encodeURIComponent(sessionId) + "/input", "POST", body, signal);
  }
  submitToolResults(sessionId: string, body: ToolResultsRequest, signal?: AbortSignal): Promise<SessionResponse> {
    return this.request<SessionResponse>("/v1/sessions/" + encodeURIComponent(sessionId) + "/tool-results", "POST", body, signal);
  }
  cancelSession(sessionId: string, signal?: AbortSignal): Promise<SessionResponse> {
    return this.request<SessionResponse>("/v1/sessions/" + encodeURIComponent(sessionId) + "/cancel", "POST", undefined, signal);
  }
  embeddingProfiles(signal?: AbortSignal): Promise<EmbeddingProfilesResponse> {
    return this.request<EmbeddingProfilesResponse>("/v1/embedding-profiles", "GET", undefined, signal);
  }
  embed(body: EmbeddingRequest, signal?: AbortSignal): Promise<EmbeddingResponse> {
    return this.request<EmbeddingResponse>("/v1/embeddings", "POST", body, signal);
  }
}
