"""Generate OpenAPI and typed client declarations from the canonical gateway schemas."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from local_agent_runtime.api_contract import OPERATIONS, SCHEMAS, openapi

ROOT = Path(__file__).resolve().parents[1]


def ts(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts(value) for value in schema["anyOf"])
    kind = schema.get("type")
    if isinstance(kind, list):
        return " | ".join(ts({"type": value}) for value in kind)
    if kind == "array":
        return "Array<" + ts(schema["items"]) + ">"
    if kind == "object":
        if "properties" not in schema:
            return "Record<string, " + ts(schema.get("additionalProperties", {})) + ">"
        required = schema.get("required", [])
        fields = []
        for name, value in schema["properties"].items():
            optional = "" if name in required else "?"
            fields.append(json.dumps(name) + optional + ": " + ts(value))
        return "{ " + "; ".join(fields) + " }"
    return {
        "string": "string",
        "number": "number",
        "integer": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown")


def client() -> str:
    lines = [
        "// Generated by scripts/generate_contracts.py. Do not edit.",
        'import { RuntimeTransport } from "./transport.js";',
        "",
    ]
    lines.extend(
        "export type " + name + " = " + ts(schema) + ";" for name, schema in SCHEMAS.items()
    )
    lines.append("\nexport class RuntimeClient extends RuntimeTransport {")
    for name, method, path, request, response in OPERATIONS:
        args = []
        if "{session_id}" in path:
            args.append("sessionId: string")
        if request:
            args.append("body: " + request)
        if name == "profiles":
            args.append("includeHealth = false")
        if name == "adapters":
            args.append("probe = false")
        if name == "events":
            args.append("after = 0")
        args.append("signal?: AbortSignal")
        if name == "profiles":
            # Appended after `signal` so `profiles(true, controller.signal)` keeps working.
            args.append("includeDiscovery = false")
        url = json.dumps(path).replace("{session_id}", '" + encodeURIComponent(sessionId) + "')
        if name == "profiles":
            url += (
                ' + "?health=" + String(includeHealth) + "&discovery=" + String(includeDiscovery)'
            )
        if name == "events":
            url += ' + "?after=" + String(after)'
        if name == "adapters":
            url += ' + "?probe=" + String(probe)'
        lines.extend(
            [
                "  " + name + "(" + ", ".join(args) + "): Promise<" + response + "> {",
                "    return this.request<"
                + response
                + ">("
                + url
                + ", "
                + json.dumps(method.upper())
                + ", "
                + ("body" if request else "undefined")
                + ", signal);",
                "  }",
            ]
        )
    lines.extend(["}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    artifacts = {
        ROOT / "contracts/openapi.json": json.dumps(openapi(), indent=2, sort_keys=True) + "\n",
        ROOT / "clients/typescript/src/generated.ts": client(),
    }
    for path, content in artifacts.items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                raise SystemExit("Generated runtime contracts are stale")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    print(
        "Generated contracts are current."
        if args.check
        else "Generated OpenAPI and TypeScript client."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
